### ISSUE TITLE
Project name could be more unique to improve search-ability and discoverability

### ISSUE THREAD

**Issue by ip2k** [paypal/support#4]
"support" is very very generic in itself, "python support" doesn't help much, and "paypal support" definitely doesn't lead to this. This doesn't even make the front page for "paypal python support". I would strongly urge the project maintainers to come up with a more unique name for this.

**Comment by mahmoud** [comment]
Hey! Thanks for your interest in the project! I was waiting for someone to file this issue, and am surprised it didn't happen day-of (or as a pull request with someone sedding through the project). I wish I had time to enumerate all the ways SuPPort was a next-level name, but I'll have to settle for just a couple:

  1. The `support.Group()` is a primary entry point.
  2. It drives certain types of people nuts. Always good for memorability.
  3. It _does_ show up when searching for PayPal support, albeit not on the front page. Yet. A couple years ago, if you [searched "Mahmoud Hashemi"](https://www.google.com/search?q=mahmoud+hashemi) you got a very prominent judge and leader of Iran, [Mahmoud Hashemi Shahroudi](https://en.wikipedia.org/wiki/Mahmoud_Hashemi_Shahroudi). Now when you search "Mahmoud Hashemi" or even just "Mahmoud", [you get this](https://github.com/mahmoud). The point is, it is possible to earn search rankings. If SuPPort proves its worth, this name will net it a lot more organic growth long-term.
  4. We managed to get corporate to approve it!

That said, we're a first-things-first kind of team. SuPPort is currently 80% design and technology demonstration, so we've got much bigger fish to fry than SEO. Until that becomes a priority, you can find SuPPort by searching for "paypal support github". Or look at the [github.com/paypal](https://github.com/paypal). `pip` finds us fine, too. ;)

**Comment by mahmoud** [comment]
Also, little bit of history, it was *going* to be called **SerPort** (server+port with the support+serpent tie-in), but **SuPPort** looks way better with the double-P for PayPal and generally had way more reactions. ;)
